export const blogs = [
  {
    id: "1",
    title: "First Blog Post",
    image: "/images/blog2.jpg",
    date: "January 1, 2025", // Date of the blog post
    description:
      "This is a short description of the blog post. It briefly summarizes the main idea of the post in just one paragraph.", // Short description
    content: `
      <h1>Main Title</h1>
      <p>This is the first blog post. It has multiple lines.</p>
      <h2>Subheading</h2>
      <p>Here is a longer description with <strong>bold text</strong> and <em>italic text</em>.</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Id velit atque excepturi deleniti nostrum minus saepe maiores ea nulla consequatur ipsam optio mollitia doloremque, ut, similique minima quae commodi? Ex, numquam quas ad enim id a expedita alias corporis consequatur perspiciatis eius minima necessitatibus laborum modi, exercitationem blanditiis nesciunt soluta accusantium reiciendis iste vel in fugiat assumenda. Error dolorum esse voluptatibus laborum consequatur dignissimos porro temporibus amet quis dolorem quo unde aut eligendi nesciunt eum tempora voluptatem ex asperiores incidunt dolor, quaerat earum. A adipisci quis, dolor voluptatem autem excepturi vitae, iste, consectetur ipsum quas beatae quaerat sed. Repellendus accusantium expedita, commodi enim non fuga deleniti numquam possimus libero quo mollitia delectus ratione illum recusandae voluptate repellat reprehenderit, accusamus soluta harum eius consequatur omnis! Facere, voluptatum repellat ratione omnis consequatur fugiat itaque voluptate illo nulla esse voluptates sint facilis. Voluptatem, ipsa rerum dolor tenetur excepturi exercitationem alias odio veritatis nihil aut ea eligendi! Vitae animi perspiciatis, molestias assumenda ipsa quae voluptates mollitia possimus reiciendis dicta architecto molestiae odit magni nesciunt cum sapiente alias? Molestiae, commodi cumque esse quaerat libero voluptate doloribus maxime doloremque minus! Eveniet iure, illo dolorem temporibus dolore consequuntur reiciendis corrupti possimus quaerat molestiae voluptas inventore molestias minima nisi tenetur repellendus magnam aperiam vitae laudantium voluptatem. Provident veritatis repellat, id a dolorem nulla commodi in error officia quia debitis quaerat, tempora nihil sint? Velit veniam quibusdam ipsum modi. Ad dignissimos sapiente vero debitis, autem atque facere nisi nihil, at, aliquam quod ratione. Aut omnis debitis aliquam deleniti autem repellat, tenetur aperiam totam! Architecto doloribus nisi, quasi maxime ratione reiciendis. Cupiditate doloremque, corporis fugiat sequi, itaque adipisci maiores suscipit deserunt incidunt facilis enim eos reiciendis dicta est laboriosam excepturi velit sit molestiae, ad quos! Labore illum quidem aperiam deleniti voluptate, at a dolor? Illo laudantium quo deserunt ducimus. Quis.</p>
      <h1>Main Title</h1>
      <p>This is the first blog post. It has multiple lines.</p>
      <h2>Subheading</h2>
      <p>Here is a longer description with <strong>bold text</strong> and <em>italic text</em>.</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Id velit atque excepturi deleniti nostrum minus saepe maiores ea nulla consequatur ipsam optio mollitia doloremque, ut, similique minima quae commodi? Ex, numquam quas ad enim id a expedita alias corporis consequatur perspiciatis eius minima necessitatibus laborum modi, exercitationem blanditiis nesciunt soluta accusantium reiciendis iste vel in fugiat assumenda. Error dolorum esse voluptatibus laborum consequatur dignissimos porro temporibus amet quis dolorem quo unde aut eligendi nesciunt eum tempora voluptatem ex asperiores incidunt dolor, quaerat earum. A adipisci quis, dolor voluptatem autem excepturi vitae, iste, consectetur ipsum quas beatae quaerat sed. Repellendus accusantium expedita, commodi enim non fuga deleniti numquam possimus libero quo mollitia delectus ratione illum recusandae voluptate repellat reprehenderit, accusamus soluta harum eius consequatur omnis! Facere, voluptatum repellat ratione omnis consequatur fugiat itaque voluptate illo nulla esse voluptates sint facilis. Voluptatem, ipsa rerum dolor tenetur excepturi exercitationem alias odio veritatis nihil aut ea eligendi! Vitae animi perspiciatis, molestias assumenda ipsa quae voluptates mollitia possimus reiciendis dicta architecto molestiae odit magni nesciunt cum sapiente alias? Molestiae, commodi cumque esse quaerat libero voluptate doloribus maxime doloremque minus! Eveniet iure, illo dolorem temporibus dolore consequuntur reiciendis corrupti possimus quaerat molestiae voluptas inventore molestias minima nisi tenetur repellendus magnam aperiam vitae laudantium voluptatem. Provident veritatis repellat, id a dolorem nulla commodi in error officia quia debitis quaerat, tempora nihil sint? Velit veniam quibusdam ipsum modi. Ad dignissimos sapiente vero debitis, autem atque facere nisi nihil, at, aliquam quod ratione. Aut omnis debitis aliquam deleniti autem repellat, tenetur aperiam totam! Architecto doloribus nisi, quasi maxime ratione reiciendis. Cupiditate doloremque, corporis fugiat sequi, itaque adipisci maiores suscipit deserunt incidunt facilis enim eos reiciendis dicta est laboriosam excepturi velit sit molestiae, ad quos! Labore illum quidem aperiam deleniti voluptate, at a dolor? Illo laudantium quo deserunt ducimus. Quis.</p>
      <h1>Main Title</h1>
      <p>This is the first blog post. It has multiple lines.</p>
      <h2>Subheading</h2>
      <p>Here is a longer description with <strong>bold text</strong> and <em>italic text</em>.</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Id velit atque excepturi deleniti nostrum minus saepe maiores ea nulla consequatur ipsam optio mollitia doloremque, ut, similique minima quae commodi? Ex, numquam quas ad enim id a expedita alias corporis consequatur perspiciatis eius minima necessitatibus laborum modi, exercitationem blanditiis nesciunt soluta accusantium reiciendis iste vel in fugiat assumenda. Error dolorum esse voluptatibus laborum consequatur dignissimos porro temporibus amet quis dolorem quo unde aut eligendi nesciunt eum tempora voluptatem ex asperiores incidunt dolor, quaerat earum. A adipisci quis, dolor voluptatem autem excepturi vitae, iste, consectetur ipsum quas beatae quaerat sed. Repellendus accusantium expedita, commodi enim non fuga deleniti numquam possimus libero quo mollitia delectus ratione illum recusandae voluptate repellat reprehenderit, accusamus soluta harum eius consequatur omnis! Facere, voluptatum repellat ratione omnis consequatur fugiat itaque voluptate illo nulla esse voluptates sint facilis. Voluptatem, ipsa rerum dolor tenetur excepturi exercitationem alias odio veritatis nihil aut ea eligendi! Vitae animi perspiciatis, molestias assumenda ipsa quae voluptates mollitia possimus reiciendis dicta architecto molestiae odit magni nesciunt cum sapiente alias? Molestiae, commodi cumque esse quaerat libero voluptate doloribus maxime doloremque minus! Eveniet iure, illo dolorem temporibus dolore consequuntur reiciendis corrupti possimus quaerat molestiae voluptas inventore molestias minima nisi tenetur repellendus magnam aperiam vitae laudantium voluptatem. Provident veritatis repellat, id a dolorem nulla commodi in error officia quia debitis quaerat, tempora nihil sint? Velit veniam quibusdam ipsum modi. Ad dignissimos sapiente vero debitis, autem atque facere nisi nihil, at, aliquam quod ratione. Aut omnis debitis aliquam deleniti autem repellat, tenetur aperiam totam! Architecto doloribus nisi, quasi maxime ratione reiciendis. Cupiditate doloremque, corporis fugiat sequi, itaque adipisci maiores suscipit deserunt incidunt facilis enim eos reiciendis dicta est laboriosam excepturi velit sit molestiae, ad quos! Labore illum quidem aperiam deleniti voluptate, at a dolor? Illo laudantium quo deserunt ducimus. Quis.</p>
    `,
  },
  {
    id: "2",
    title: "Second Blog Post",
    image: "/images/blog2.jpg",
    date: "February 5, 2025",
    description:
      "This is another short description of a different blog post, summarizing the content in one paragraph.",
    content: `
      <h1>Main Title</h1>
      <p>This is the first blog post. It has multiple lines.</p>
      <h2>Subheading</h2>
      <p>Here is a longer description with <strong>bold text</strong> and <em>italic text</em>.</p>
      <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Magni delectus, fugit, molestiae laboriosam error saepe alias vero veritatis dolores ipsum beatae enim fugiat sunt in suscipit facere minima? Ratione nobis dolor dolorem quidem laudantium soluta cum, ut aliquid consequatur itaque rerum exercitationem accusantium placeat error possimus suscipit quod molestias. Impedit odio in nihil aut et! Qui, dolorum ut nesciunt suscipit eum voluptas quod fuga possimus! Vero, voluptatem. Optio, excepturi autem vel, rerum officiis cupiditate fuga amet fugit natus iste dolor nesciunt consequuntur architecto perspiciatis vero quaerat ad est, sapiente nulla molestias asperiores modi at. Voluptatum earum repellendus amet a perferendis?</p>
      <h1>Main Title</h1>
      <p>This is the first blog post. It has multiple lines.</p>
      <h2>Subheading</h2>
      <p>Here is a longer description with <strong>bold text</strong> and <em>italic text</em>.</p>
      <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Magni delectus, fugit, molestiae laboriosam error saepe alias vero veritatis dolores ipsum beatae enim fugiat sunt in suscipit facere minima? Ratione nobis dolor dolorem quidem laudantium soluta cum, ut aliquid consequatur itaque rerum exercitationem accusantium placeat error possimus suscipit quod molestias. Impedit odio in nihil aut et! Qui, dolorum ut nesciunt suscipit eum voluptas quod fuga possimus! Vero, voluptatem. Optio, excepturi autem vel, rerum officiis cupiditate fuga amet fugit natus iste dolor nesciunt consequuntur architecto perspiciatis vero quaerat ad est, sapiente nulla molestias asperiores modi at. Voluptatum earum repellendus amet a perferendis?</p>
      <h1>Main Title</h1>
      <p>This is the first blog post. It has multiple lines.</p>
      <h2>Subheading</h2>
      <p>Here is a longer description with <strong>bold text</strong> and <em>italic text</em>.</p>
      <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Magni delectus, fugit, molestiae laboriosam error saepe alias vero veritatis dolores ipsum beatae enim fugiat sunt in suscipit facere minima? Ratione nobis dolor dolorem quidem laudantium soluta cum, ut aliquid consequatur itaque rerum exercitationem accusantium placeat error possimus suscipit quod molestias. Impedit odio in nihil aut et! Qui, dolorum ut nesciunt suscipit eum voluptas quod fuga possimus! Vero, voluptatem. Optio, excepturi autem vel, rerum officiis cupiditate fuga amet fugit natus iste dolor nesciunt consequuntur architecto perspiciatis vero quaerat ad est, sapiente nulla molestias asperiores modi at. Voluptatum earum repellendus amet a perferendis?</p>
    `,
  },
  {
    id: "3",
    title: "First Blog Post",
    image: "/images/blog2.jpg",
    date: "January 1, 2025", // Date of the blog post
    description:
      "This is a short description of the blog post. It briefly summarizes the main idea of the post in just one paragraph.", // Short description
    content: `
      <h1>Main Title</h1>
      <p>This is the first blog post. It has multiple lines.</p>
      <h2>Subheading</h2>
      <p>Here is a longer description with <strong>bold text</strong> and <em>italic text</em>.</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Id velit atque excepturi deleniti nostrum minus saepe maiores ea nulla consequatur ipsam optio mollitia doloremque, ut, similique minima quae commodi? Ex, numquam quas ad enim id a expedita alias corporis consequatur perspiciatis eius minima necessitatibus laborum modi, exercitationem blanditiis nesciunt soluta accusantium reiciendis iste vel in fugiat assumenda. Error dolorum esse voluptatibus laborum consequatur dignissimos porro temporibus amet quis dolorem quo unde aut eligendi nesciunt eum tempora voluptatem ex asperiores incidunt dolor, quaerat earum. A adipisci quis, dolor voluptatem autem excepturi vitae, iste, consectetur ipsum quas beatae quaerat sed. Repellendus accusantium expedita, commodi enim non fuga deleniti numquam possimus libero quo mollitia delectus ratione illum recusandae voluptate repellat reprehenderit, accusamus soluta harum eius consequatur omnis! Facere, voluptatum repellat ratione omnis consequatur fugiat itaque voluptate illo nulla esse voluptates sint facilis. Voluptatem, ipsa rerum dolor tenetur excepturi exercitationem alias odio veritatis nihil aut ea eligendi! Vitae animi perspiciatis, molestias assumenda ipsa quae voluptates mollitia possimus reiciendis dicta architecto molestiae odit magni nesciunt cum sapiente alias? Molestiae, commodi cumque esse quaerat libero voluptate doloribus maxime doloremque minus! Eveniet iure, illo dolorem temporibus dolore consequuntur reiciendis corrupti possimus quaerat molestiae voluptas inventore molestias minima nisi tenetur repellendus magnam aperiam vitae laudantium voluptatem. Provident veritatis repellat, id a dolorem nulla commodi in error officia quia debitis quaerat, tempora nihil sint? Velit veniam quibusdam ipsum modi. Ad dignissimos sapiente vero debitis, autem atque facere nisi nihil, at, aliquam quod ratione. Aut omnis debitis aliquam deleniti autem repellat, tenetur aperiam totam! Architecto doloribus nisi, quasi maxime ratione reiciendis. Cupiditate doloremque, corporis fugiat sequi, itaque adipisci maiores suscipit deserunt incidunt facilis enim eos reiciendis dicta est laboriosam excepturi velit sit molestiae, ad quos! Labore illum quidem aperiam deleniti voluptate, at a dolor? Illo laudantium quo deserunt ducimus. Quis.</p>
      <h1>Main Title</h1>
      <p>This is the first blog post. It has multiple lines.</p>
      <h2>Subheading</h2>
      <p>Here is a longer description with <strong>bold text</strong> and <em>italic text</em>.</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Id velit atque excepturi deleniti nostrum minus saepe maiores ea nulla consequatur ipsam optio mollitia doloremque, ut, similique minima quae commodi? Ex, numquam quas ad enim id a expedita alias corporis consequatur perspiciatis eius minima necessitatibus laborum modi, exercitationem blanditiis nesciunt soluta accusantium reiciendis iste vel in fugiat assumenda. Error dolorum esse voluptatibus laborum consequatur dignissimos porro temporibus amet quis dolorem quo unde aut eligendi nesciunt eum tempora voluptatem ex asperiores incidunt dolor, quaerat earum. A adipisci quis, dolor voluptatem autem excepturi vitae, iste, consectetur ipsum quas beatae quaerat sed. Repellendus accusantium expedita, commodi enim non fuga deleniti numquam possimus libero quo mollitia delectus ratione illum recusandae voluptate repellat reprehenderit, accusamus soluta harum eius consequatur omnis! Facere, voluptatum repellat ratione omnis consequatur fugiat itaque voluptate illo nulla esse voluptates sint facilis. Voluptatem, ipsa rerum dolor tenetur excepturi exercitationem alias odio veritatis nihil aut ea eligendi! Vitae animi perspiciatis, molestias assumenda ipsa quae voluptates mollitia possimus reiciendis dicta architecto molestiae odit magni nesciunt cum sapiente alias? Molestiae, commodi cumque esse quaerat libero voluptate doloribus maxime doloremque minus! Eveniet iure, illo dolorem temporibus dolore consequuntur reiciendis corrupti possimus quaerat molestiae voluptas inventore molestias minima nisi tenetur repellendus magnam aperiam vitae laudantium voluptatem. Provident veritatis repellat, id a dolorem nulla commodi in error officia quia debitis quaerat, tempora nihil sint? Velit veniam quibusdam ipsum modi. Ad dignissimos sapiente vero debitis, autem atque facere nisi nihil, at, aliquam quod ratione. Aut omnis debitis aliquam deleniti autem repellat, tenetur aperiam totam! Architecto doloribus nisi, quasi maxime ratione reiciendis. Cupiditate doloremque, corporis fugiat sequi, itaque adipisci maiores suscipit deserunt incidunt facilis enim eos reiciendis dicta est laboriosam excepturi velit sit molestiae, ad quos! Labore illum quidem aperiam deleniti voluptate, at a dolor? Illo laudantium quo deserunt ducimus. Quis.</p>
      <h1>Main Title</h1>
      <p>This is the first blog post. It has multiple lines.</p>
      <h2>Subheading</h2>
      <p>Here is a longer description with <strong>bold text</strong> and <em>italic text</em>.</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Id velit atque excepturi deleniti nostrum minus saepe maiores ea nulla consequatur ipsam optio mollitia doloremque, ut, similique minima quae commodi? Ex, numquam quas ad enim id a expedita alias corporis consequatur perspiciatis eius minima necessitatibus laborum modi, exercitationem blanditiis nesciunt soluta accusantium reiciendis iste vel in fugiat assumenda. Error dolorum esse voluptatibus laborum consequatur dignissimos porro temporibus amet quis dolorem quo unde aut eligendi nesciunt eum tempora voluptatem ex asperiores incidunt dolor, quaerat earum. A adipisci quis, dolor voluptatem autem excepturi vitae, iste, consectetur ipsum quas beatae quaerat sed. Repellendus accusantium expedita, commodi enim non fuga deleniti numquam possimus libero quo mollitia delectus ratione illum recusandae voluptate repellat reprehenderit, accusamus soluta harum eius consequatur omnis! Facere, voluptatum repellat ratione omnis consequatur fugiat itaque voluptate illo nulla esse voluptates sint facilis. Voluptatem, ipsa rerum dolor tenetur excepturi exercitationem alias odio veritatis nihil aut ea eligendi! Vitae animi perspiciatis, molestias assumenda ipsa quae voluptates mollitia possimus reiciendis dicta architecto molestiae odit magni nesciunt cum sapiente alias? Molestiae, commodi cumque esse quaerat libero voluptate doloribus maxime doloremque minus! Eveniet iure, illo dolorem temporibus dolore consequuntur reiciendis corrupti possimus quaerat molestiae voluptas inventore molestias minima nisi tenetur repellendus magnam aperiam vitae laudantium voluptatem. Provident veritatis repellat, id a dolorem nulla commodi in error officia quia debitis quaerat, tempora nihil sint? Velit veniam quibusdam ipsum modi. Ad dignissimos sapiente vero debitis, autem atque facere nisi nihil, at, aliquam quod ratione. Aut omnis debitis aliquam deleniti autem repellat, tenetur aperiam totam! Architecto doloribus nisi, quasi maxime ratione reiciendis. Cupiditate doloremque, corporis fugiat sequi, itaque adipisci maiores suscipit deserunt incidunt facilis enim eos reiciendis dicta est laboriosam excepturi velit sit molestiae, ad quos! Labore illum quidem aperiam deleniti voluptate, at a dolor? Illo laudantium quo deserunt ducimus. Quis.</p>
    `,
  },
  {
    id: "4",
    title: "Second Blog Post",
    image: "/images/blog2.jpg",
    date: "February 5, 2025",
    description:
      "This is another short description of a different blog post, summarizing the content in one paragraph.",
    content: `
      <h1>Main Title</h1>
      <p>This is the first blog post. It has multiple lines.</p>
      <h2>Subheading</h2>
      <p>Here is a longer description with <strong>bold text</strong> and <em>italic text</em>.</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Id velit atque excepturi deleniti nostrum minus saepe maiores ea nulla consequatur ipsam optio mollitia doloremque, ut, similique minima quae commodi? Ex, numquam quas ad enim id a expedita alias corporis consequatur perspiciatis eius minima necessitatibus laborum modi, exercitationem blanditiis nesciunt soluta accusantium reiciendis iste vel in fugiat assumenda. Error dolorum esse voluptatibus laborum consequatur dignissimos porro temporibus amet quis dolorem quo unde aut eligendi nesciunt eum tempora voluptatem ex asperiores incidunt dolor, quaerat earum. A adipisci quis, dolor voluptatem autem excepturi vitae, iste, consectetur ipsum quas beatae quaerat sed. Repellendus accusantium expedita, commodi enim non fuga deleniti numquam possimus libero quo mollitia delectus ratione illum recusandae voluptate repellat reprehenderit, accusamus soluta harum eius consequatur omnis! Facere, voluptatum repellat ratione omnis consequatur fugiat itaque voluptate illo nulla esse voluptates sint facilis. Voluptatem, ipsa rerum dolor tenetur excepturi exercitationem alias odio veritatis nihil aut ea eligendi! Vitae animi perspiciatis, molestias assumenda ipsa quae voluptates mollitia possimus reiciendis dicta architecto molestiae odit magni nesciunt cum sapiente alias? Molestiae, commodi cumque esse quaerat libero voluptate doloribus maxime doloremque minus! Eveniet iure, illo dolorem temporibus dolore consequuntur reiciendis corrupti possimus quaerat molestiae voluptas inventore molestias minima nisi tenetur repellendus magnam aperiam vitae laudantium voluptatem. Provident veritatis repellat, id a dolorem nulla commodi in error officia quia debitis quaerat, tempora nihil sint? Velit veniam quibusdam ipsum modi. Ad dignissimos sapiente vero debitis, autem atque facere nisi nihil, at, aliquam quod ratione. Aut omnis debitis aliquam deleniti autem repellat, tenetur aperiam totam! Architecto doloribus nisi, quasi maxime ratione reiciendis. Cupiditate doloremque, corporis fugiat sequi, itaque adipisci maiores suscipit deserunt incidunt facilis enim eos reiciendis dicta est laboriosam excepturi velit sit molestiae, ad quos! Labore illum quidem aperiam deleniti voluptate, at a dolor? Illo laudantium quo deserunt ducimus. Quis.</p>
      <h1>Main Title</h1>
      <p>This is the first blog post. It has multiple lines.</p>
      <h2>Subheading</h2>
      <p>Here is a longer description with <strong>bold text</strong> and <em>italic text</em>.</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Id velit atque excepturi deleniti nostrum minus saepe maiores ea nulla consequatur ipsam optio mollitia doloremque, ut, similique minima quae commodi? Ex, numquam quas ad enim id a expedita alias corporis consequatur perspiciatis eius minima necessitatibus laborum modi, exercitationem blanditiis nesciunt soluta accusantium reiciendis iste vel in fugiat assumenda. Error dolorum esse voluptatibus laborum consequatur dignissimos porro temporibus amet quis dolorem quo unde aut eligendi nesciunt eum tempora voluptatem ex asperiores incidunt dolor, quaerat earum. A adipisci quis, dolor voluptatem autem excepturi vitae, iste, consectetur ipsum quas beatae quaerat sed. Repellendus accusantium expedita, commodi enim non fuga deleniti numquam possimus libero quo mollitia delectus ratione illum recusandae voluptate repellat reprehenderit, accusamus soluta harum eius consequatur omnis! Facere, voluptatum repellat ratione omnis consequatur fugiat itaque voluptate illo nulla esse voluptates sint facilis. Voluptatem, ipsa rerum dolor tenetur excepturi exercitationem alias odio veritatis nihil aut ea eligendi! Vitae animi perspiciatis, molestias assumenda ipsa quae voluptates mollitia possimus reiciendis dicta architecto molestiae odit magni nesciunt cum sapiente alias? Molestiae, commodi cumque esse quaerat libero voluptate doloribus maxime doloremque minus! Eveniet iure, illo dolorem temporibus dolore consequuntur reiciendis corrupti possimus quaerat molestiae voluptas inventore molestias minima nisi tenetur repellendus magnam aperiam vitae laudantium voluptatem. Provident veritatis repellat, id a dolorem nulla commodi in error officia quia debitis quaerat, tempora nihil sint? Velit veniam quibusdam ipsum modi. Ad dignissimos sapiente vero debitis, autem atque facere nisi nihil, at, aliquam quod ratione. Aut omnis debitis aliquam deleniti autem repellat, tenetur aperiam totam! Architecto doloribus nisi, quasi maxime ratione reiciendis. Cupiditate doloremque, corporis fugiat sequi, itaque adipisci maiores suscipit deserunt incidunt facilis enim eos reiciendis dicta est laboriosam excepturi velit sit molestiae, ad quos! Labore illum quidem aperiam deleniti voluptate, at a dolor? Illo laudantium quo deserunt ducimus. Quis.</p>
      <h1>Main Title</h1>
      <p>This is the first blog post. It has multiple lines.</p>
      <h2>Subheading</h2>
      <p>Here is a longer description with <strong>bold text</strong> and <em>italic text</em>.</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Id velit atque excepturi deleniti nostrum minus saepe maiores ea nulla consequatur ipsam optio mollitia doloremque, ut, similique minima quae commodi? Ex, numquam quas ad enim id a expedita alias corporis consequatur perspiciatis eius minima necessitatibus laborum modi, exercitationem blanditiis nesciunt soluta accusantium reiciendis iste vel in fugiat assumenda. Error dolorum esse voluptatibus laborum consequatur dignissimos porro temporibus amet quis dolorem quo unde aut eligendi nesciunt eum tempora voluptatem ex asperiores incidunt dolor, quaerat earum. A adipisci quis, dolor voluptatem autem excepturi vitae, iste, consectetur ipsum quas beatae quaerat sed. Repellendus accusantium expedita, commodi enim non fuga deleniti numquam possimus libero quo mollitia delectus ratione illum recusandae voluptate repellat reprehenderit, accusamus soluta harum eius consequatur omnis! Facere, voluptatum repellat ratione omnis consequatur fugiat itaque voluptate illo nulla esse voluptates sint facilis. Voluptatem, ipsa rerum dolor tenetur excepturi exercitationem alias odio veritatis nihil aut ea eligendi! Vitae animi perspiciatis, molestias assumenda ipsa quae voluptates mollitia possimus reiciendis dicta architecto molestiae odit magni nesciunt cum sapiente alias? Molestiae, commodi cumque esse quaerat libero voluptate doloribus maxime doloremque minus! Eveniet iure, illo dolorem temporibus dolore consequuntur reiciendis corrupti possimus quaerat molestiae voluptas inventore molestias minima nisi tenetur repellendus magnam aperiam vitae laudantium voluptatem. Provident veritatis repellat, id a dolorem nulla commodi in error officia quia debitis quaerat, tempora nihil sint? Velit veniam quibusdam ipsum modi. Ad dignissimos sapiente vero debitis, autem atque facere nisi nihil, at, aliquam quod ratione. Aut omnis debitis aliquam deleniti autem repellat, tenetur aperiam totam! Architecto doloribus nisi, quasi maxime ratione reiciendis. Cupiditate doloremque, corporis fugiat sequi, itaque adipisci maiores suscipit deserunt incidunt facilis enim eos reiciendis dicta est laboriosam excepturi velit sit molestiae, ad quos! Labore illum quidem aperiam deleniti voluptate, at a dolor? Illo laudantium quo deserunt ducimus. Quis.</p>
    `,
  },
  {
    id: "5",
    title: "First Blog Post",
    image: "/images/blog2.jpg",
    date: "January 1, 2025", // Date of the blog post
    description:
      "This is a short description of the blog post. It briefly summarizes the main idea of the post in just one paragraph.", // Short description
    content: `
      <h1>Main Title</h1>
      <p>This is the first blog post. It has multiple lines.</p>
      <h2>Subheading</h2>
      <p>Here is a longer description with <strong>bold text</strong> and <em>italic text</em>.</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Id velit atque excepturi deleniti nostrum minus saepe maiores ea nulla consequatur ipsam optio mollitia doloremque, ut, similique minima quae commodi? Ex, numquam quas ad enim id a expedita alias corporis consequatur perspiciatis eius minima necessitatibus laborum modi, exercitationem blanditiis nesciunt soluta accusantium reiciendis iste vel in fugiat assumenda. Error dolorum esse voluptatibus laborum consequatur dignissimos porro temporibus amet quis dolorem quo unde aut eligendi nesciunt eum tempora voluptatem ex asperiores incidunt dolor, quaerat earum. A adipisci quis, dolor voluptatem autem excepturi vitae, iste, consectetur ipsum quas beatae quaerat sed. Repellendus accusantium expedita, commodi enim non fuga deleniti numquam possimus libero quo mollitia delectus ratione illum recusandae voluptate repellat reprehenderit, accusamus soluta harum eius consequatur omnis! Facere, voluptatum repellat ratione omnis consequatur fugiat itaque voluptate illo nulla esse voluptates sint facilis. Voluptatem, ipsa rerum dolor tenetur excepturi exercitationem alias odio veritatis nihil aut ea eligendi! Vitae animi perspiciatis, molestias assumenda ipsa quae voluptates mollitia possimus reiciendis dicta architecto molestiae odit magni nesciunt cum sapiente alias? Molestiae, commodi cumque esse quaerat libero voluptate doloribus maxime doloremque minus! Eveniet iure, illo dolorem temporibus dolore consequuntur reiciendis corrupti possimus quaerat molestiae voluptas inventore molestias minima nisi tenetur repellendus magnam aperiam vitae laudantium voluptatem. Provident veritatis repellat, id a dolorem nulla commodi in error officia quia debitis quaerat, tempora nihil sint? Velit veniam quibusdam ipsum modi. Ad dignissimos sapiente vero debitis, autem atque facere nisi nihil, at, aliquam quod ratione. Aut omnis debitis aliquam deleniti autem repellat, tenetur aperiam totam! Architecto doloribus nisi, quasi maxime ratione reiciendis. Cupiditate doloremque, corporis fugiat sequi, itaque adipisci maiores suscipit deserunt incidunt facilis enim eos reiciendis dicta est laboriosam excepturi velit sit molestiae, ad quos! Labore illum quidem aperiam deleniti voluptate, at a dolor? Illo laudantium quo deserunt ducimus. Quis.</p>
      <h1>Main Title</h1>
      <p>This is the first blog post. It has multiple lines.</p>
      <h2>Subheading</h2>
      <p>Here is a longer description with <strong>bold text</strong> and <em>italic text</em>.</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Id velit atque excepturi deleniti nostrum minus saepe maiores ea nulla consequatur ipsam optio mollitia doloremque, ut, similique minima quae commodi? Ex, numquam quas ad enim id a expedita alias corporis consequatur perspiciatis eius minima necessitatibus laborum modi, exercitationem blanditiis nesciunt soluta accusantium reiciendis iste vel in fugiat assumenda. Error dolorum esse voluptatibus laborum consequatur dignissimos porro temporibus amet quis dolorem quo unde aut eligendi nesciunt eum tempora voluptatem ex asperiores incidunt dolor, quaerat earum. A adipisci quis, dolor voluptatem autem excepturi vitae, iste, consectetur ipsum quas beatae quaerat sed. Repellendus accusantium expedita, commodi enim non fuga deleniti numquam possimus libero quo mollitia delectus ratione illum recusandae voluptate repellat reprehenderit, accusamus soluta harum eius consequatur omnis! Facere, voluptatum repellat ratione omnis consequatur fugiat itaque voluptate illo nulla esse voluptates sint facilis. Voluptatem, ipsa rerum dolor tenetur excepturi exercitationem alias odio veritatis nihil aut ea eligendi! Vitae animi perspiciatis, molestias assumenda ipsa quae voluptates mollitia possimus reiciendis dicta architecto molestiae odit magni nesciunt cum sapiente alias? Molestiae, commodi cumque esse quaerat libero voluptate doloribus maxime doloremque minus! Eveniet iure, illo dolorem temporibus dolore consequuntur reiciendis corrupti possimus quaerat molestiae voluptas inventore molestias minima nisi tenetur repellendus magnam aperiam vitae laudantium voluptatem. Provident veritatis repellat, id a dolorem nulla commodi in error officia quia debitis quaerat, tempora nihil sint? Velit veniam quibusdam ipsum modi. Ad dignissimos sapiente vero debitis, autem atque facere nisi nihil, at, aliquam quod ratione. Aut omnis debitis aliquam deleniti autem repellat, tenetur aperiam totam! Architecto doloribus nisi, quasi maxime ratione reiciendis. Cupiditate doloremque, corporis fugiat sequi, itaque adipisci maiores suscipit deserunt incidunt facilis enim eos reiciendis dicta est laboriosam excepturi velit sit molestiae, ad quos! Labore illum quidem aperiam deleniti voluptate, at a dolor? Illo laudantium quo deserunt ducimus. Quis.</p>
      <h1>Main Title</h1>
      <p>This is the first blog post. It has multiple lines.</p>
      <h2>Subheading</h2>
      <p>Here is a longer description with <strong>bold text</strong> and <em>italic text</em>.</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Id velit atque excepturi deleniti nostrum minus saepe maiores ea nulla consequatur ipsam optio mollitia doloremque, ut, similique minima quae commodi? Ex, numquam quas ad enim id a expedita alias corporis consequatur perspiciatis eius minima necessitatibus laborum modi, exercitationem blanditiis nesciunt soluta accusantium reiciendis iste vel in fugiat assumenda. Error dolorum esse voluptatibus laborum consequatur dignissimos porro temporibus amet quis dolorem quo unde aut eligendi nesciunt eum tempora voluptatem ex asperiores incidunt dolor, quaerat earum. A adipisci quis, dolor voluptatem autem excepturi vitae, iste, consectetur ipsum quas beatae quaerat sed. Repellendus accusantium expedita, commodi enim non fuga deleniti numquam possimus libero quo mollitia delectus ratione illum recusandae voluptate repellat reprehenderit, accusamus soluta harum eius consequatur omnis! Facere, voluptatum repellat ratione omnis consequatur fugiat itaque voluptate illo nulla esse voluptates sint facilis. Voluptatem, ipsa rerum dolor tenetur excepturi exercitationem alias odio veritatis nihil aut ea eligendi! Vitae animi perspiciatis, molestias assumenda ipsa quae voluptates mollitia possimus reiciendis dicta architecto molestiae odit magni nesciunt cum sapiente alias? Molestiae, commodi cumque esse quaerat libero voluptate doloribus maxime doloremque minus! Eveniet iure, illo dolorem temporibus dolore consequuntur reiciendis corrupti possimus quaerat molestiae voluptas inventore molestias minima nisi tenetur repellendus magnam aperiam vitae laudantium voluptatem. Provident veritatis repellat, id a dolorem nulla commodi in error officia quia debitis quaerat, tempora nihil sint? Velit veniam quibusdam ipsum modi. Ad dignissimos sapiente vero debitis, autem atque facere nisi nihil, at, aliquam quod ratione. Aut omnis debitis aliquam deleniti autem repellat, tenetur aperiam totam! Architecto doloribus nisi, quasi maxime ratione reiciendis. Cupiditate doloremque, corporis fugiat sequi, itaque adipisci maiores suscipit deserunt incidunt facilis enim eos reiciendis dicta est laboriosam excepturi velit sit molestiae, ad quos! Labore illum quidem aperiam deleniti voluptate, at a dolor? Illo laudantium quo deserunt ducimus. Quis.</p>
    `,
  },
  {
    id: "6",
    title: "Second Blog Post",
    image: "/images/blog2.jpg",
    date: "February 5, 2025",
    description:
      "This is another short description of a different blog post, summarizing the content in one paragraph.",
    content: `
      <h1>Main Title</h1>
      <p>This is the first blog post. It has multiple lines.</p>
      <h2>Subheading</h2>
      <p>Here is a longer description with <strong>bold text</strong> and <em>italic text</em>.</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Id velit atque excepturi deleniti nostrum minus saepe maiores ea nulla consequatur ipsam optio mollitia doloremque, ut, similique minima quae commodi? Ex, numquam quas ad enim id a expedita alias corporis consequatur perspiciatis eius minima necessitatibus laborum modi, exercitationem blanditiis nesciunt soluta accusantium reiciendis iste vel in fugiat assumenda. Error dolorum esse voluptatibus laborum consequatur dignissimos porro temporibus amet quis dolorem quo unde aut eligendi nesciunt eum tempora voluptatem ex asperiores incidunt dolor, quaerat earum. A adipisci quis, dolor voluptatem autem excepturi vitae, iste, consectetur ipsum quas beatae quaerat sed. Repellendus accusantium expedita, commodi enim non fuga deleniti numquam possimus libero quo mollitia delectus ratione illum recusandae voluptate repellat reprehenderit, accusamus soluta harum eius consequatur omnis! Facere, voluptatum repellat ratione omnis consequatur fugiat itaque voluptate illo nulla esse voluptates sint facilis. Voluptatem, ipsa rerum dolor tenetur excepturi exercitationem alias odio veritatis nihil aut ea eligendi! Vitae animi perspiciatis, molestias assumenda ipsa quae voluptates mollitia possimus reiciendis dicta architecto molestiae odit magni nesciunt cum sapiente alias? Molestiae, commodi cumque esse quaerat libero voluptate doloribus maxime doloremque minus! Eveniet iure, illo dolorem temporibus dolore consequuntur reiciendis corrupti possimus quaerat molestiae voluptas inventore molestias minima nisi tenetur repellendus magnam aperiam vitae laudantium voluptatem. Provident veritatis repellat, id a dolorem nulla commodi in error officia quia debitis quaerat, tempora nihil sint? Velit veniam quibusdam ipsum modi. Ad dignissimos sapiente vero debitis, autem atque facere nisi nihil, at, aliquam quod ratione. Aut omnis debitis aliquam deleniti autem repellat, tenetur aperiam totam! Architecto doloribus nisi, quasi maxime ratione reiciendis. Cupiditate doloremque, corporis fugiat sequi, itaque adipisci maiores suscipit deserunt incidunt facilis enim eos reiciendis dicta est laboriosam excepturi velit sit molestiae, ad quos! Labore illum quidem aperiam deleniti voluptate, at a dolor? Illo laudantium quo deserunt ducimus. Quis.</p>
      <h1>Main Title</h1>
      <p>This is the first blog post. It has multiple lines.</p>
      <h2>Subheading</h2>
      <p>Here is a longer description with <strong>bold text</strong> and <em>italic text</em>.</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Id velit atque excepturi deleniti nostrum minus saepe maiores ea nulla consequatur ipsam optio mollitia doloremque, ut, similique minima quae commodi? Ex, numquam quas ad enim id a expedita alias corporis consequatur perspiciatis eius minima necessitatibus laborum modi, exercitationem blanditiis nesciunt soluta accusantium reiciendis iste vel in fugiat assumenda. Error dolorum esse voluptatibus laborum consequatur dignissimos porro temporibus amet quis dolorem quo unde aut eligendi nesciunt eum tempora voluptatem ex asperiores incidunt dolor, quaerat earum. A adipisci quis, dolor voluptatem autem excepturi vitae, iste, consectetur ipsum quas beatae quaerat sed. Repellendus accusantium expedita, commodi enim non fuga deleniti numquam possimus libero quo mollitia delectus ratione illum recusandae voluptate repellat reprehenderit, accusamus soluta harum eius consequatur omnis! Facere, voluptatum repellat ratione omnis consequatur fugiat itaque voluptate illo nulla esse voluptates sint facilis. Voluptatem, ipsa rerum dolor tenetur excepturi exercitationem alias odio veritatis nihil aut ea eligendi! Vitae animi perspiciatis, molestias assumenda ipsa quae voluptates mollitia possimus reiciendis dicta architecto molestiae odit magni nesciunt cum sapiente alias? Molestiae, commodi cumque esse quaerat libero voluptate doloribus maxime doloremque minus! Eveniet iure, illo dolorem temporibus dolore consequuntur reiciendis corrupti possimus quaerat molestiae voluptas inventore molestias minima nisi tenetur repellendus magnam aperiam vitae laudantium voluptatem. Provident veritatis repellat, id a dolorem nulla commodi in error officia quia debitis quaerat, tempora nihil sint? Velit veniam quibusdam ipsum modi. Ad dignissimos sapiente vero debitis, autem atque facere nisi nihil, at, aliquam quod ratione. Aut omnis debitis aliquam deleniti autem repellat, tenetur aperiam totam! Architecto doloribus nisi, quasi maxime ratione reiciendis. Cupiditate doloremque, corporis fugiat sequi, itaque adipisci maiores suscipit deserunt incidunt facilis enim eos reiciendis dicta est laboriosam excepturi velit sit molestiae, ad quos! Labore illum quidem aperiam deleniti voluptate, at a dolor? Illo laudantium quo deserunt ducimus. Quis.</p>
      <h1>Main Title</h1>
      <p>This is the first blog post. It has multiple lines.</p>
      <h2>Subheading</h2>
      <p>Here is a longer description with <strong>bold text</strong> and <em>italic text</em>.</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Id velit atque excepturi deleniti nostrum minus saepe maiores ea nulla consequatur ipsam optio mollitia doloremque, ut, similique minima quae commodi? Ex, numquam quas ad enim id a expedita alias corporis consequatur perspiciatis eius minima necessitatibus laborum modi, exercitationem blanditiis nesciunt soluta accusantium reiciendis iste vel in fugiat assumenda. Error dolorum esse voluptatibus laborum consequatur dignissimos porro temporibus amet quis dolorem quo unde aut eligendi nesciunt eum tempora voluptatem ex asperiores incidunt dolor, quaerat earum. A adipisci quis, dolor voluptatem autem excepturi vitae, iste, consectetur ipsum quas beatae quaerat sed. Repellendus accusantium expedita, commodi enim non fuga deleniti numquam possimus libero quo mollitia delectus ratione illum recusandae voluptate repellat reprehenderit, accusamus soluta harum eius consequatur omnis! Facere, voluptatum repellat ratione omnis consequatur fugiat itaque voluptate illo nulla esse voluptates sint facilis. Voluptatem, ipsa rerum dolor tenetur excepturi exercitationem alias odio veritatis nihil aut ea eligendi! Vitae animi perspiciatis, molestias assumenda ipsa quae voluptates mollitia possimus reiciendis dicta architecto molestiae odit magni nesciunt cum sapiente alias? Molestiae, commodi cumque esse quaerat libero voluptate doloribus maxime doloremque minus! Eveniet iure, illo dolorem temporibus dolore consequuntur reiciendis corrupti possimus quaerat molestiae voluptas inventore molestias minima nisi tenetur repellendus magnam aperiam vitae laudantium voluptatem. Provident veritatis repellat, id a dolorem nulla commodi in error officia quia debitis quaerat, tempora nihil sint? Velit veniam quibusdam ipsum modi. Ad dignissimos sapiente vero debitis, autem atque facere nisi nihil, at, aliquam quod ratione. Aut omnis debitis aliquam deleniti autem repellat, tenetur aperiam totam! Architecto doloribus nisi, quasi maxime ratione reiciendis. Cupiditate doloremque, corporis fugiat sequi, itaque adipisci maiores suscipit deserunt incidunt facilis enim eos reiciendis dicta est laboriosam excepturi velit sit molestiae, ad quos! Labore illum quidem aperiam deleniti voluptate, at a dolor? Illo laudantium quo deserunt ducimus. Quis.</p>
    `,
  },
];
